name: auro
description: "A generative art mood tracker."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  hive_flutter: ^1.1.0
  go_router: ^14.8.0
  google_fonts: ^6.2.1
  intl: ^0.20.2
  uuid: ^4.5.1
  glassmorphism: ^3.0.0
  hive: ^2.2.3
  table_calendar: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.5.4

flutter:
  uses-material-design: true
